# Generated by Django 6.0 on 2025-12-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
