# Generated by Django 4.2.23 on 2025-12-05 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "horilla_core",
            "0003_horillauserprofile_alter_businesshour_week_days_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoringcondition",
            name="company",
        ),
        migrations.RemoveField(
            model_name="scoringcondition",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="scoringcondition",
            name="criterion",
        ),
        migrations.RemoveField(
            model_name="scoringcondition",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="scoringcriterion",
            name="company",
        ),
        migrations.RemoveField(
            model_name="scoringcriterion",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="scoringcriterion",
            name="rule",
        ),
        migrations.RemoveField(
            model_name="scoringcriterion",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="scoringrule",
            name="company",
        ),
        migrations.RemoveField(
            model_name="scoringrule",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="scoringrule",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="EmailActivityScoring",
        ),
        migrations.DeleteModel(
            name="ScoringCondition",
        ),
        migrations.DeleteModel(
            name="ScoringCriterion",
        ),
        migrations.DeleteModel(
            name="ScoringRule",
        ),
    ]
