# Generated by Django 6.0 on 2025-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0005_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbangroupby',
            name='model_name',
            field=models.CharField(help_text="Name of the model (e.g., 'User') to group by.", max_length=100),
        ),
    ]
