# Generated by Django 6.0 on 2025-12-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunitysplittype_split_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitysplit',
            options={'verbose_name': 'Opportunity Split', 'verbose_name_plural': 'Opportunity Splits'},
        ),
    ]
