# Generated by Django 4.2.23 on 2025-12-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_alter_lead_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="lead_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead",
                to="leads.leadstatus",
                verbose_name="Lead Stage",
            ),
        ),
    ]
