# Generated by Django 6.0 on 2025-12-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtoleadconfig',
            options={'verbose_name': 'Mail to Lead Config', 'verbose_name_plural': 'Mail to Lead Config'},
        ),
    ]
