# Generated by Django 6.0 on 2025-12-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_emailtoleadconfig_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email_message_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='message_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
