# Generated by Django 6.0 on 2025-12-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_reports', '0002_alter_report_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfolder',
            options={'verbose_name': 'Report Folder', 'verbose_name_plural': 'Report Folders'},
        ),
    ]
