# Generated by Django 4.2.23 on 2025-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horilla_mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horillamailconfiguration",
            name="mail_channel",
            field=models.CharField(
                choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                help_text="Specifies whether this configuration handles incoming,outgoing, or both types of emails.",
                max_length=20,
                verbose_name="Mail Channel",
            ),
        ),
    ]
