# Generated by Django 6.0 on 2025-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_mail', '0002_alter_horillamailconfiguration_mail_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='horillamailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
    ]
